apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: boot-otel-tempo-provider1
  name: boot-otel-tempo-provider1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: boot-otel-tempo-provider1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: boot-otel-tempo-provider1
    spec:
      containers:
        - env:
            - name: PROVIDER1_DB_PASS
              value: postgrespassword
            - name: PROVIDER1_DB_URL
              value: jdbc:postgresql://provider1-db:5432/provider1
            - name: PROVIDER1_DB_USER
              value: postgres
          image: kisaron5/otel-tempo-provider1:v1
          name: boot-otel-tempo-provider1
          ports:
            - containerPort: 8090
          resources: {}
          volumeMounts:
            - mountPath: /app/logs
              name: boot-otel-tempo-provider1-claim0
      restartPolicy: Always
      volumes:
        - name: boot-otel-tempo-provider1-claim0
          hostPath:
            path: /root/boot-opentelemetry-tempo/data/logs
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: boot-otel-tempo-provider1
  name: boot-otel-tempo-provider1
spec:
  ports:
    - name: "8090"
      port: 8090
      targetPort: 8090
  selector:
    io.kompose.service: boot-otel-tempo-provider1
status:
  loadBalancer: {}