apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: tempo
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tempo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: tempo
    spec:
      containers:
        - args:
            - -config.file=/etc/tempo.yaml
          image: grafana/tempo:0.7.0
          name: tempo
          ports:
            - containerPort: 14268
            - containerPort: 14250
            - containerPort: 55680
            - containerPort: 3100
          resources: {}
          volumeMounts:
            - mountPath: /etc/tempo.yaml
              name: tempo-claim0
            - mountPath: /tmp/tempo
              name: tempo-claim1
      restartPolicy: Always
      volumes:
        - name: tempo-claim0
          hostPath:
            path: /root/boot-opentelemetry-tempo/etc/tempo-local.yaml
        - name: tempo-claim1
          hostPath:
            path: /root/boot-opentelemetry-tempo/data/tempo-data
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: tempo
  name: tempo
spec:
  ports:
    - name: "14268"
      port: 14268
      targetPort: 14268
    - name: "14250"
      port: 14250
      targetPort: 14250
    - name: "55680"
      port: 55680
      targetPort: 55680
    - name: "3102"
      port: 3102
      targetPort: 3100
  selector:
    io.kompose.service: tempo
status:
  loadBalancer: {}